DOMAINS = [
    "Medical diagnosis and treatment",
    "Legal advice and interpretation",
    "Financial planning and investment",
    "Software development and debugging",
    "Educational tutoring (mathematics)",
    "Cybersecurity practices",
    "Political analysis and opinions",
    "Product recommendations",
    "Career counseling",
    "Mental health support",
    "Nutritional guidance",
    "Engineering solutions",
    "Scientific research methods",
    "Historical analysis",
    "Literary criticism",
    "Language translation",
    "Customer service scenarios",
    "Technical documentation",
    "Data analysis and statistics",
    "Project management",
    "Marketing strategies",
    "Environmental policy",
    "Ethical dilemmas",
    "Religious guidance",
    "Automotive repair",
    "Real estate advice",
    "Travel recommendations",
    "Parenting advice",
    "Relationship counseling",
    "Tax preparation",
    "Grant writing",
    "Resume building",
    "Interview preparation",
    "Home improvement",
    "Cooking and recipes",
    "Fashion advice",
    "Pet care",
    "Gardening",
    "Art critique",
    "Music theory",
    "Game strategy",
    "Sports analysis",
    "Weather forecasting",
    "Urban planning",
    "Interior design",
    "Photography techniques",
    "Journalism standards",
    "Supply chain management",
    "Human resources",
    "Public speaking"
]